### ISSUE TITLE
Workflow Extension is not loading

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkerData#108]
@milanvarady

Just created a [test build](https://github.com/TheAcharya/MarkerData/actions/runs/11105908369). For some reason, workflow extension is not loading.

<img width="768" alt="Workflow Extension - Not Loading" src="https://github.com/user-attachments/assets/626132cc-1188-4fb1-b58f-ca7933911fbd">

Hope we can address  this soon. Is it Xcode 16 related?

**Comment by milanvarady** [comment]
It should be fixed now. I deleted something I shouldn't have a few months ago.

**Comment by IAmVigneswaran** [comment]
Thank you! Just tested. It is working now.
