### ISSUE TITLE
Shortcuts for Configurations

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkerData#47]
@milanvarady Would it be possible to assign shortcut to Configurations?

We can have a `Assign Shortcut` menu when right-clicking Configurations.

<img width="577" alt="configuration-shortcuts-01" src="https://github.com/TheAcharya/MarkerData/assets/118706051/2cdd2676-e553-43a8-a239-cc8032663053">

Once assigned, the shortcuts would appear on Configurations menu.

<img width="357" alt="configuration-shortcuts-02" src="https://github.com/TheAcharya/MarkerData/assets/118706051/12ba66a2-c708-4785-ab9b-664eb5d86aed">

Users can easily switch between Configurations by press, `⌘ + 1`, `⌘ + 3` , `⌘ + 3` .... `⌘ + 9`
Users can have up to 9 assignable shortcuts.

**Comment by IAmVigneswaran** [comment]
@milanvarady Let's aim "assign shortcut to Configurations" feature for 1.1.0 by end of Nov - Dec.

Thank you.

**Comment by milanvarady** [comment]
I have implemented the configuration shortcuts. This is how it looks like:

![CleanShot 2024-11-01 at 21 12 05](https://github.com/user-attachments/assets/9c16d655-10c9-4e0d-9710-b9a7062e87f8)

![CleanShot 2024-11-01 at 21 12 44](https://github.com/user-attachments/assets/735880a9-b814-4fe0-bb58-e648017d84f4)

**Comment by IAmVigneswaran** [comment]
@milanvarady Thank you for adding the shortcuts feature for configuration! From this [test-build](https://github.com/TheAcharya/MarkerData/actions/runs/11635786474) seems to be working. 

But how would users, un-assign? Can clicking same sub-menu item, would un-assign the shortcut?

**Comment by milanvarady** [comment]
Currently you can't unassgn only override. I can add that feature if you want.

**Comment by IAmVigneswaran** [comment]
> Currently you can't unassgn only override. I can add that feature if you want.

That would be great! Thank you.

**Comment by milanvarady** [comment]
I have added unassign functionality.

**Comment by IAmVigneswaran** [comment]
@milanvarady It is possible to tweak it slightly.

Right now the `✓` checkmark replaces `⌘` when assigned.

```
✓ 1
⌘ 2
⌘ 3
⌘ 4
⌘ 5
⌘ 6
⌘ 7
⌘ 8
⌘ 9
```

Could we do like this? If assigned, `✓` would appear beside.

```
  ⌘ 1
✓ ⌘ 2
  ⌘ 3
  ⌘ 4
  ⌘ 5
  ⌘ 6
  ⌘ 7
  ⌘ 8
  ⌘ 9
```

<hr>

I noticed a bug. Right now, you can assign more than one shortcut to any given configuration.

<img width="508" alt="configuration-shortcut-bug" src="https://github.com/user-attachments/assets/036240fe-604c-4861-8200-edee3a73d001">

I believe the logic should be as such -  Say we have 3 configuration. `Config 1`, `Config 2` and `Config 3` And All these have been assigned from `⌘ 1`, `⌘ 2` and `⌘ 3` respectively.

If user re-assigns`Config 1` to `⌘ 3`, automatically, `Config 3`'s shortcut will be un-assigned.

**Comment by milanvarady** [comment]
I have fixed the assign behavior and added the checkmark.

**Comment by IAmVigneswaran** [comment]
> I have fixed the assign behavior and added the checkmark.

Thank you! Perfect!
