### ISSUE TITLE
Show Update Badge in Menu Bar

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkerData#94]
@milanvarady Would it be possible to show a `New Version Available` badge beside `Check for Updates...` in the application menu bar, if there is a an update available? 

In an event user cancels an update, at least the user knows it is available?

<img width="322" alt="update-menu" src="https://github.com/TheAcharya/MarkerData/assets/118706051/2cf8871c-abd3-42ee-8eae-13a625cf4c89">

<br>
<br>

<img width="333" alt="update-badge" src="https://github.com/TheAcharya/MarkerData/assets/118706051/d4d801f8-8583-4e5b-8d0c-e51f06eb6935">

**Comment by IAmVigneswaran** [comment]
@milanvarady I notice a minor bug. 

For some reason, the `update badge` does not show up again after the app is restarted. It only show up once.

**Comment by milanvarady** [comment]
The checking wasn't consistent, so I used a different method. It should work now every time.

**Comment by IAmVigneswaran** [comment]
> The checking wasn't consistent, so I used a different method. It should work now every time.

Thanks for the fix! It is working now.
